[package]
name = "parsekoto"
version = "1.0.0"
description = "csv parser for motoko"
repository = "https://github.com/c0utin/parsekoto"
keywords = [ "csv", "parser", "serde", "ai", "data-science", "data" ]
license = "MIT"

[dependencies]
base = "0.12.0"
itertools = "0.2.2"
serde = "3.2.1"
candid = "1.0.2"
"json.mo" = "0.1.2"
